### ISSUE TITLE
Dynamic list of IPs to block

### ISSUE THREAD

**Issue by edasque** [kevtainer/denyip#2]
Is there any way the plugin could read the IPs from a file? That would be easier to maintain with a fail2ban type setup than changing them in the config file, I beleive.

**Comment by notsureifkevin** [comment]
At the moment, this wouldn't be possible since the interpreter used in Traefik blocks syscalls (which would be required to read a file from disk). There are plans to open some of these up, but it has to be done safely while disallowing calls like `exec`, `kill`, `exit`, etc.

**Comment by kvncrw** [comment]
There are no plans to include this functionality. Feel free to fork this repository, if someone is referencing this issue later perhaps you could build something that pulls an IP list in from an API or some other data source (just not the filesystem, unless that's a possibility now with the plugin interpreter).
