### ISSUE TITLE
Combining with `ipWhiteList` middleware

### ISSUE THREAD

**Issue by shalak** [kevtainer/denyip#8]
How does this DenyIP work with the native `ipWhiteList` middleware? 

What takes precedence, if I have same IP address on both lists? 

What about in a case when I have a CIDR network address on one, but single IP on the other?

**Comment by kvncrw** [comment]
Hi @shalak, were you able to find the answers to the above questions?

My assumption is that the native middleware would be evaluated first, but it's been a couple years since I've worked with Traefik or the middleware routines.

Cheers!
